[tox]
minversion = 4.0
skip_missing_interpreters = true
envlist =
    lint
    coverage

toxworkdir = {env:TOX_WORKDIR:.tox}

[gh-actions]
python =
    3.14: lint, coverage

[testenv]
basepython = python3.14

[testenv:lint]
description = Lint the project.
setenv =
    DJANGO_SETTINGS_MODULE=mregsite.settings
    CI=True
passenv = MREG_*, GITHUB_*
skip_install = true
deps = ruff
allowlist_externals = ruff
commands = ruff check .

[testenv:coverage]
runner = uv-venv-lock-runner
dependency_groups = 
    dev
    ci
description = Report the coverage of the project.
setenv =
    DJANGO_SETTINGS_MODULE=mregsite.settings
    CI=True
passenv = MREG_*, GITHUB_*
commands =
    python --version
    python -m django --version
    coverage run --concurrency=multiprocessing manage.py test --parallel
    coverage run --concurrency=multiprocessing -m pytest
    coverage combine
    coverage report -m


[coverage:report]
fail_under = 97
show_missing = true
exclude_also =
    'pragma: no cover'
    'def __repr__'

[coverage:run]
omit =
    manage.py
    */migrations/*
    mreg/api/tests/test_metrics.py
    # omit anything in a .local, venv/* directory anywhere
    */.local/*
    venv/*
    env/*
    */.virtualenvs/*
    */virtualenv/*

[coverage:html]
directory = coverage_html_report
