# Generated by Django 2.2.5 on 2019-09-24 11:49

import datetime
from django.db import migrations, models
import hostpolicy.models
import mreg.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HostPolicyAtom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('create_date', models.DateField(default=datetime.date.today)),
                ('description', models.CharField(max_length=150)),
                ('name', mreg.fields.LCICharField(max_length=64, unique=True, validators=[hostpolicy.models._validate_atom_name])),
            ],
            options={
                'db_table': 'hostpolicy_atom',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='HostPolicyRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('create_date', models.DateField(default=datetime.date.today)),
                ('description', models.CharField(max_length=150)),
                ('name', mreg.fields.LCICharField(max_length=64, unique=True, validators=[hostpolicy.models._validate_role_name])),
                ('atoms', models.ManyToManyField(related_name='roles', to='hostpolicy.HostPolicyAtom')),
            ],
            options={
                'db_table': 'hostpolicy_role',
                'ordering': ('name',),
            },
        ),
    ]
