# Generated by Django 2.2.5 on 2019-09-24 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hostpolicy', '0001_initial'),
        ('mreg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostpolicyrole',
            name='hosts',
            field=models.ManyToManyField(related_name='hostpolicyroles', to='mreg.Host'),
        ),
    ]
