# Generated by Django 3.2.18 on 2023-06-29 09:26

from django.db import migrations
import hostpolicy.models
import mreg.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hostpolicy', '0003_hostpolicyrole_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostpolicyatom',
            name='name',
            field=mreg.fields.LowerCaseCharField(max_length=64, unique=True, validators=[hostpolicy.models._validate_atom_name]),
        ),
        migrations.AlterField(
            model_name='hostpolicyrole',
            name='name',
            field=mreg.fields.LowerCaseCharField(max_length=64, unique=True, validators=[hostpolicy.models._validate_role_name]),
        ),
    ]
