# Generated by Django 6.0.7 on 2026-09-24 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hostpolicy", "0004_migrate_away_from_ci_fields"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="hostpolicyatom",
            options={"ordering": ("name",), "verbose_name": "atom"},
        ),
        migrations.AlterModelOptions(
            name="hostpolicyrole",
            options={"ordering": ("name",), "verbose_name": "role"},
        ),
    ]
