# Generated by Django 2.0.6 on 2018-06-28 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hosts',
            fields=[
                ('hostid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(unique=True)),
                ('ipaddress', models.GenericIPAddressField(unique=True)),
                ('ttl', models.IntegerField(blank=True, null=True)),
                ('macaddress', models.TextField(blank=True, null=True)),
                ('contact', models.TextField()),
                ('hinfo', models.TextField(blank=True, null=True)),
                ('loc', models.TextField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'hosts',
            },
        ),
    ]
