from django.urls import path

from . import views

urlpatterns = [
    path('cnames/', views.CnameList.as_view()),
    path('cnames/<name>', views.CnameDetail.as_view()),
    path('dhcphosts/v4/all', views.DhcpHostsAllV4.as_view()),
    path('dhcphosts/v6/all', views.DhcpHostsAllV6.as_view()),
    path('dhcphosts/<ip>/<range>', views.DhcpHostsByRange.as_view()),
    path('hinfopresets/', views.HinfoPresetList.as_view()),
    path('hinfopresets/<pk>', views.HinfoPresetDetail.as_view()),
    path('hosts/', views.HostList.as_view()),
    path('hosts/<pk>', views.HostDetail.as_view()),
    path('ipaddresses/', views.IpaddressList.as_view()),
    path('ipaddresses/<pk>', views.IpaddressDetail.as_view()),
    path('naptrs/', views.NaptrList.as_view()),
    path('naptrs/<pk>', views.NaptrDetail.as_view()),
    path('nameservers/', views.NameServerList.as_view()),
    path('nameservers/<pk>', views.NameServerDetail.as_view()),
    path('ptroverrides/', views.PtrOverrideList.as_view()),
    path('ptroverrides/<pk>', views.PtrOverrideDetail.as_view()),
    path('srvs/', views.SrvList.as_view()),
    path('srvs/<pk>', views.SrvDetail.as_view()),
    path('subnets/', views.SubnetList.as_view()),
    path('subnets/<ip>/<range>', views.SubnetDetail.as_view()),
    path('txts/', views.TxtList.as_view()),
    path('txts/<pk>', views.TxtDetail.as_view()),
    path('zones/', views.ZoneList.as_view()),
    path('zones/<name>', views.ZoneDetail.as_view()),
    path('zones/<name>/nameservers', views.ZoneNameServerDetail.as_view()),
    path('zonefiles/<pk>', views.ZoneFileDetail.as_view()),
    path('history/', views.ModelChangeLogList.as_view()),
    path('history/<table>/<pk>', views.ModelChangeLogDetail.as_view()),
]
