# Generated by Django 2.1.2 on 2018-12-14 10:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mreg.utils
import mreg.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cname',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('ttl', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cname',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='HinfoPreset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu', models.TextField()),
                ('os', models.TextField()),
            ],
            options={
                'db_table': 'hinfo_preset',
            },
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=253, unique=True, validators=[mreg.validators.validate_hostname])),
                ('contact', models.EmailField(max_length=254)),
                ('ttl', models.IntegerField(blank=True, null=True)),
                ('loc', models.TextField(blank=True, validators=[mreg.validators.validate_loc])),
                ('comment', models.TextField(blank=True)),
                ('hinfo', models.ForeignKey(blank=True, db_column='hinfo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mreg.HinfoPreset')),
            ],
            options={
                'db_table': 'host',
            },
        ),
        migrations.CreateModel(
            name='HostGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostgroup_name', models.CharField(max_length=50, unique=True)),
                ('parent', models.ManyToManyField(blank=True, related_name='groups', to='mreg.HostGroup')),
            ],
        ),
        migrations.CreateModel(
            name='HostGroupMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mreg.HostGroup')),
                ('hostid', models.ForeignKey(db_column='hostid', on_delete=django.db.models.deletion.PROTECT, related_name='hostgroupmember', to='mreg.Host')),
            ],
        ),
        migrations.CreateModel(
            name='Ipaddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipaddress', models.GenericIPAddressField()),
                ('macaddress', models.CharField(blank=True, max_length=17, validators=[mreg.validators.validate_mac_address])),
                ('host', models.ForeignKey(db_column='host', on_delete=django.db.models.deletion.CASCADE, related_name='ipaddresses', to='mreg.Host')),
            ],
            options={
                'db_table': 'ipaddress',
            },
        ),
        migrations.CreateModel(
            name='ModelChangeLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=132)),
                ('table_row', models.BigIntegerField()),
                ('data', models.TextField()),
                ('action', models.CharField(max_length=16)),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'db_table': 'model_change_log',
            },
        ),
        migrations.CreateModel(
            name='NameServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=253, unique=True, validators=[mreg.validators.validate_hostname])),
                ('ttl', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ns',
            },
        ),
        migrations.CreateModel(
            name='Naptr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preference', models.IntegerField(validators=[mreg.validators.validate_16bit_uint])),
                ('order', models.IntegerField(validators=[mreg.validators.validate_16bit_uint])),
                ('flag', models.CharField(blank=True, max_length=1, validators=[mreg.validators.validate_naptr_flag])),
                ('service', models.CharField(blank=True, max_length=255)),
                ('regex', models.TextField(blank=True)),
                ('replacement', models.CharField(max_length=255)),
                ('host', models.ForeignKey(db_column='host', on_delete=django.db.models.deletion.CASCADE, related_name='naptrs', to='mreg.Host')),
            ],
            options={
                'db_table': 'naptr',
                'ordering': ('preference', 'order', 'flag', 'service', 'regex', 'replacement'),
            },
        ),
        migrations.CreateModel(
            name='PtrOverride',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipaddress', models.GenericIPAddressField(unique=True)),
                ('host', models.ForeignKey(db_column='host', on_delete=django.db.models.deletion.CASCADE, related_name='ptr_overrides', to='mreg.Host')),
            ],
            options={
                'db_table': 'ptr_override',
            },
        ),
        migrations.CreateModel(
            name='Srv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(validators=[mreg.validators.validate_srv_service_text])),
                ('priority', models.IntegerField(validators=[mreg.validators.validate_16bit_uint])),
                ('weight', models.IntegerField(validators=[mreg.validators.validate_16bit_uint])),
                ('port', models.IntegerField(validators=[mreg.validators.validate_16bit_uint])),
                ('ttl', models.IntegerField(blank=True, null=True)),
                ('target', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'srv',
                'ordering': ('name', 'priority', 'weight', 'port', 'target'),
            },
        ),
        migrations.CreateModel(
            name='Subnet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('range', models.TextField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('vlan', models.IntegerField(blank=True, null=True)),
                ('dns_delegated', models.NullBooleanField()),
                ('category', models.TextField(blank=True)),
                ('location', models.TextField(blank=True)),
                ('frozen', models.NullBooleanField()),
                ('reserved', models.PositiveIntegerField(default=3)),
            ],
            options={
                'db_table': 'subnet',
                'ordering': ('range',),
            },
        ),
        migrations.CreateModel(
            name='Txt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txt', models.TextField(max_length=255)),
                ('host', models.ForeignKey(db_column='host', on_delete=django.db.models.deletion.CASCADE, related_name='txts', to='mreg.Host')),
            ],
            options={
                'db_table': 'txt',
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=253, unique=True, validators=[mreg.validators.validate_zonename])),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('primary_ns', models.CharField(max_length=253, validators=[mreg.validators.validate_hostname])),
                ('email', models.EmailField(max_length=254)),
                ('serialno', models.BigIntegerField(default=mreg.utils.create_serialno, validators=[mreg.validators.validate_zones_serialno])),
                ('serialno_updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('refresh', models.IntegerField(default=10800)),
                ('retry', models.IntegerField(default=3600)),
                ('expire', models.IntegerField(default=1814400)),
                ('ttl', models.IntegerField(default=43200)),
                ('nameservers', models.ManyToManyField(db_column='ns', to='mreg.NameServer')),
            ],
            options={
                'db_table': 'zone',
            },
        ),
        migrations.AddField(
            model_name='srv',
            name='zone',
            field=models.ForeignKey(blank=True, db_column='zone', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mreg.Zone'),
        ),
        migrations.AddField(
            model_name='host',
            name='zone',
            field=models.ForeignKey(blank=True, db_column='zone', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mreg.Zone'),
        ),
        migrations.AlterUniqueTogether(
            name='hinfopreset',
            unique_together={('cpu', 'os')},
        ),
        migrations.AddField(
            model_name='cname',
            name='host',
            field=models.ForeignKey(db_column='host', on_delete=django.db.models.deletion.CASCADE, related_name='cnames', to='mreg.Host'),
        ),
        migrations.AddField(
            model_name='cname',
            name='zone',
            field=models.ForeignKey(blank=True, db_column='zone', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mreg.Zone'),
        ),
        migrations.AlterUniqueTogether(
            name='txt',
            unique_together={('host', 'txt')},
        ),
        migrations.AlterUniqueTogether(
            name='srv',
            unique_together={('name', 'priority', 'weight', 'port', 'target')},
        ),
        migrations.AlterUniqueTogether(
            name='naptr',
            unique_together={('host', 'preference', 'order', 'flag', 'service', 'regex', 'replacement')},
        ),
        migrations.AlterUniqueTogether(
            name='ipaddress',
            unique_together={('host', 'ipaddress')},
        ),
    ]
