# Generated by Django 2.0.6 on 2018-07-06 08:55

from django.db import migrations, models
import django.db.models.deletion
import mreg.validators


class Migration(migrations.Migration):

    dependencies = [
        ('mreg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cname',
            name='hostid',
            field=models.ForeignKey(db_column='hostid', on_delete=django.db.models.deletion.DO_NOTHING, related_name='cname', to='mreg.Hosts'),
        ),
        migrations.AlterField(
            model_name='ipaddress',
            name='hostid',
            field=models.ForeignKey(db_column='hostid', on_delete=django.db.models.deletion.DO_NOTHING, related_name='ipaddress', to='mreg.Hosts'),
        ),
        migrations.AlterField(
            model_name='naptr',
            name='hostid',
            field=models.ForeignKey(db_column='hostid', on_delete=django.db.models.deletion.DO_NOTHING, related_name='naptr', to='mreg.Hosts'),
        ),
        migrations.AlterField(
            model_name='ptroverride',
            name='hostid',
            field=models.ForeignKey(db_column='hostid', on_delete=django.db.models.deletion.DO_NOTHING, related_name='ptr_override', to='mreg.Hosts'),
        ),
        migrations.AlterField(
            model_name='txt',
            name='hostid',
            field=models.ForeignKey(db_column='hostid', on_delete=django.db.models.deletion.DO_NOTHING, related_name='txt', to='mreg.Hosts'),
        ),
        migrations.AlterField(
            model_name='zones',
            name='serialno',
            field=models.BigIntegerField(blank=True, null=True, validators=[mreg.validators.validate_zones_serialno]),
        ),
    ]
