# Generated by Django 2.2 on 2019-04-09 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mreg', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='netgroupregexpermission',
            unique_together={('group', 'range', 'regex')},
        ),
    ]
