# Generated by Django 2.0.6 on 2018-06-29 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mreg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cname',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.TextField()),
                ('ttl', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cname',
            },
        ),
        migrations.CreateModel(
            name='HinfoPresets',
            fields=[
                ('hinfoid', models.AutoField(primary_key=True, serialize=False)),
                ('cpu', models.TextField()),
                ('os', models.TextField()),
            ],
            options={
                'db_table': 'hinfo_presets',
            },
        ),
        migrations.CreateModel(
            name='Ipaddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipaddress', models.GenericIPAddressField(unique=True)),
                ('macaddress', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ipaddress',
            },
        ),
        migrations.CreateModel(
            name='Naptr',
            fields=[
                ('naptrid', models.AutoField(primary_key=True, serialize=False)),
                ('preference', models.IntegerField(blank=True, null=True)),
                ('orderv', models.IntegerField(blank=True, null=True)),
                ('flag', models.CharField(blank=True, max_length=1, null=True)),
                ('service', models.TextField()),
                ('regex', models.TextField(blank=True, null=True)),
                ('replacement', models.TextField()),
            ],
            options={
                'db_table': 'naptr',
            },
        ),
        migrations.CreateModel(
            name='Ns',
            fields=[
                ('nsid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('ttl', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ns',
            },
        ),
        migrations.CreateModel(
            name='PtrOverride',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipaddress', models.GenericIPAddressField(unique=True)),
            ],
            options={
                'db_table': 'ptr_override',
            },
        ),
        migrations.CreateModel(
            name='Srv',
            fields=[
                ('srvid', models.AutoField(primary_key=True, serialize=False)),
                ('service', models.TextField()),
                ('priority', models.IntegerField(blank=True, null=True)),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('port', models.IntegerField(blank=True, null=True)),
                ('ttl', models.IntegerField(blank=True, null=True)),
                ('target', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'srv',
            },
        ),
        migrations.CreateModel(
            name='Subnets',
            fields=[
                ('subnetid', models.AutoField(primary_key=True, serialize=False)),
                ('range', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('vlan', models.IntegerField(blank=True, null=True)),
                ('dns_delegated', models.NullBooleanField()),
            ],
            options={
                'db_table': 'subnets',
            },
        ),
        migrations.CreateModel(
            name='Txt',
            fields=[
                ('txtid', models.AutoField(primary_key=True, serialize=False)),
                ('txt', models.TextField()),
            ],
            options={
                'db_table': 'txt',
            },
        ),
        migrations.CreateModel(
            name='Zones',
            fields=[
                ('zoneid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(unique=True)),
                ('primary_ns', models.TextField()),
                ('email', models.TextField(blank=True, null=True)),
                ('serialno', models.BigIntegerField(blank=True, null=True)),
                ('refresh', models.IntegerField(blank=True, null=True)),
                ('retry', models.IntegerField(blank=True, null=True)),
                ('expire', models.IntegerField(blank=True, null=True)),
                ('ttl', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'zones',
            },
        ),
        migrations.RemoveField(
            model_name='hosts',
            name='ipaddress',
        ),
        migrations.RemoveField(
            model_name='hosts',
            name='macaddress',
        ),
        migrations.AlterField(
            model_name='hosts',
            name='hinfo',
            field=models.ForeignKey(blank=True, db_column='hinfo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mreg.HinfoPresets'),
        ),
        migrations.AddField(
            model_name='txt',
            name='hostid',
            field=models.ForeignKey(db_column='hostid', on_delete=django.db.models.deletion.DO_NOTHING, to='mreg.Hosts'),
        ),
        migrations.AddField(
            model_name='ptroverride',
            name='hostid',
            field=models.ForeignKey(db_column='hostid', on_delete=django.db.models.deletion.DO_NOTHING, to='mreg.Hosts'),
        ),
        migrations.AddField(
            model_name='ns',
            name='zoneid',
            field=models.ForeignKey(db_column='zoneid', on_delete=django.db.models.deletion.DO_NOTHING, to='mreg.Zones'),
        ),
        migrations.AddField(
            model_name='ipaddress',
            name='hostid',
            field=models.ForeignKey(db_column='hostid', on_delete=django.db.models.deletion.DO_NOTHING, to='mreg.Hosts'),
        ),
        migrations.AddField(
            model_name='cname',
            name='hostid',
            field=models.ForeignKey(db_column='hostid', on_delete=django.db.models.deletion.DO_NOTHING, to='mreg.Hosts'),
        ),
    ]
