# Generated by Django 2.1.3 on 2018-12-03 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mreg', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='txt',
            unique_together={('host', 'txt')},
        ),
    ]
