# Generated by Django 2.2.6 on 2019-10-02 10:27

from django.db import migrations, models
import django.db.models.deletion
import mreg.validators


class Migration(migrations.Migration):

    dependencies = [
        ('mreg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hinfo',
            fields=[
                ('host', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mreg.Host')),
                ('cpu', models.TextField()),
                ('os', models.TextField()),
            ],
            options={
                'db_table': 'hinfo',
            },
        ),
        migrations.CreateModel(
            name='Loc',
            fields=[
                ('host', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mreg.Host')),
                ('loc', models.TextField(validators=[mreg.validators.validate_loc])),
            ],
            options={
                'db_table': 'loc',
            },
        ),
        migrations.RemoveField(
            model_name='host',
            name='hinfo',
        ),
        migrations.RemoveField(
            model_name='host',
            name='loc',
        ),
        migrations.DeleteModel(
            name='HinfoPreset',
        ),
    ]
