# Generated by Django 2.2.2 on 2019-06-12 11:50

from django.db import migrations, models
import mreg.validators


class Migration(migrations.Migration):

    dependencies = [
        ('mreg', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forwardzone',
            old_name='ttl',
            new_name='default_ttl',
        ),
        migrations.RenameField(
            model_name='reversezone',
            old_name='ttl',
            new_name='default_ttl',
        ),
        migrations.AddField(
            model_name='forwardzone',
            name='soa_ttl',
            field=models.IntegerField(default=43200, validators=[mreg.validators.validate_ttl]),
        ),
        migrations.AddField(
            model_name='reversezone',
            name='soa_ttl',
            field=models.IntegerField(default=43200, validators=[mreg.validators.validate_ttl]),
        ),
    ]
