# Generated by Django 2.2.2 on 2019-06-17 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mreg', '0002_auto_20190612_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
