# Generated by Django 2.0.6 on 2018-07-06 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mreg', '0002_auto_20180706_1055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ns',
            name='zoneid',
        ),
        migrations.AddField(
            model_name='zones',
            name='nameservers',
            field=models.ManyToManyField(to='mreg.Ns'),
        ),
    ]
