# Generated by Django 2.2 on 2019-04-11 08:52

from django.db import migrations
import netfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mreg', '0002_auto_20190409_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='netgroupregexpermission',
            name='range',
            field=netfields.fields.CidrAddressField(max_length=43),
        ),
    ]
