# Generated by Django 2.2.2 on 2019-06-10 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mreg', '0002_auto_20190528_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipaddress',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
