# Generated by Django 2.2.1 on 2019-05-28 13:02

from django.db import migrations
import netfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mreg', '0002_auto_20190528_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ptroverride',
            name='ipaddress',
            field=netfields.fields.InetAddressField(max_length=39, unique=True),
        ),
    ]
