# Generated by Django 2.2.6 on 2019-10-16 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mreg', '0002_auto_20191015_0942'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkExcludedRange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_ip', models.GenericIPAddressField(unique=True)),
                ('end_ip', models.GenericIPAddressField(unique=True)),
                ('network', models.ForeignKey(db_column='excluded_range', on_delete=django.db.models.deletion.CASCADE, related_name='excluded_ranges', to='mreg.Network')),
            ],
            options={
                'db_table': 'network_exluded_range',
                'ordering': ('start_ip',),
            },
        ),
    ]
