# Generated by Django 2.2.6 on 2019-10-24 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mreg', '0003_networkexcludedrange'),
    ]

    operations = [
        migrations.AddField(
            model_name='forwardzonedelegation',
            name='comment',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='reversezonedelegation',
            name='comment',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
