# Generated by Django 2.1.7 on 2019-02-22 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mreg', '0003_reversezone_range'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forwardzone',
            name='updated',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='reversezone',
            name='updated',
            field=models.BooleanField(default=True),
        ),
    ]
