# Generated by Django 2.2.2 on 2019-06-27 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mreg', '0003_network_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='cname',
            name='cname',
            field=models.ForeignKey(db_column='cname', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cnames', to='mreg.Cname'),
        ),
        migrations.AlterField(
            model_name='cname',
            name='host',
            field=models.ForeignKey(db_column='host', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cnames', to='mreg.Host'),
        ),
    ]
