# Generated by Django 2.1.3 on 2018-12-05 10:00

from django.db import migrations, models
import mreg.validators


class Migration(migrations.Migration):

    dependencies = [
        ('mreg', '0003_auto_20181204_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipaddress',
            name='macaddress',
            field=models.CharField(blank=True, max_length=17, validators=[mreg.validators.validate_mac_address]),
        ),
    ]
