# Generated by Django 2.0.6 on 2018-07-11 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mreg', '0003_auto_20180706_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cname',
            name='hostid',
            field=models.ForeignKey(db_column='hostid', on_delete=django.db.models.deletion.CASCADE, related_name='cname', to='mreg.Hosts'),
        ),
        migrations.AlterField(
            model_name='cname',
            name='ttl',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hosts',
            name='ttl',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ipaddress',
            name='hostid',
            field=models.ForeignKey(db_column='hostid', on_delete=django.db.models.deletion.CASCADE, related_name='ipaddress', to='mreg.Hosts'),
        ),
        migrations.AlterField(
            model_name='naptr',
            name='hostid',
            field=models.ForeignKey(db_column='hostid', on_delete=django.db.models.deletion.CASCADE, related_name='naptr', to='mreg.Hosts'),
        ),
        migrations.AlterField(
            model_name='ns',
            name='name',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='ns',
            name='ttl',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ptroverride',
            name='hostid',
            field=models.ForeignKey(db_column='hostid', on_delete=django.db.models.deletion.CASCADE, related_name='ptr_override', to='mreg.Hosts'),
        ),
        migrations.AlterField(
            model_name='srv',
            name='ttl',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='txt',
            name='hostid',
            field=models.ForeignKey(db_column='hostid', on_delete=django.db.models.deletion.CASCADE, related_name='txt', to='mreg.Hosts'),
        ),
        migrations.AlterField(
            model_name='zones',
            name='nameservers',
            field=models.ManyToManyField(db_column='ns', to='mreg.Ns'),
        ),
        migrations.AlterField(
            model_name='zones',
            name='ttl',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
