# Generated by Django 2.2.5 on 2019-09-09 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mreg', '0003_network_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelchangelog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
