# Generated by Django 2.2.1 on 2019-05-06 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mreg', '0004_auto_20190411_1427'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('parent', models.ManyToManyField(blank=True, related_name='groups', to='mreg.HostGroup')),
            ],
            options={
                'db_table': 'hostgroup',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='HostGroupMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hostmembers', to='mreg.HostGroup')),
                ('host', models.ForeignKey(db_column='host', on_delete=django.db.models.deletion.PROTECT, related_name='hostgroups', to='mreg.Host')),
            ],
            options={
                'db_table': 'hostmember',
                'ordering': ('group',),
            },
        ),
    ]
