# Generated by Django 2.0.6 on 2018-07-13 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mreg', '0004_auto_20180711_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='subnets',
            name='category',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subnets',
            name='frozen',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='subnets',
            name='location',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subnets',
            name='range',
            field=models.TextField(unique=True),
        ),
    ]
