# Generated by Django 2.0.6 on 2018-07-12 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mreg', '0004_auto_20180711_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='subnets',
            name='category',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subnets',
            name='frozen',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='subnets',
            name='location',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cname',
            name='hostid',
            field=models.ForeignKey(db_column='hostid', on_delete=django.db.models.deletion.DO_NOTHING, related_name='cname', to='mreg.Hosts'),
        ),
        migrations.AlterField(
            model_name='ipaddress',
            name='hostid',
            field=models.ForeignKey(db_column='hostid', on_delete=django.db.models.deletion.DO_NOTHING, related_name='ipaddress', to='mreg.Hosts'),
        ),
        migrations.AlterField(
            model_name='naptr',
            name='hostid',
            field=models.ForeignKey(db_column='hostid', on_delete=django.db.models.deletion.DO_NOTHING, related_name='naptr', to='mreg.Hosts'),
        ),
        migrations.AlterField(
            model_name='ptroverride',
            name='hostid',
            field=models.ForeignKey(db_column='hostid', on_delete=django.db.models.deletion.DO_NOTHING, related_name='ptr_override', to='mreg.Hosts'),
        ),
        migrations.AlterField(
            model_name='txt',
            name='hostid',
            field=models.ForeignKey(db_column='hostid', on_delete=django.db.models.deletion.DO_NOTHING, related_name='txt', to='mreg.Hosts'),
        ),
    ]
