# Generated by Django 2.2.7 on 2019-11-05 12:46

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mreg', '0004_auto_20191024_1016'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.CharField(max_length=64)),
                ('resource', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('model_id', models.PositiveIntegerField()),
                ('model', models.CharField(max_length=64)),
                ('action', models.CharField(max_length=64)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
