# Generated by Django 2.2.2 on 2019-06-28 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mreg', '0004_auto_20190627_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cname',
            name='cname',
            field=models.ForeignKey(blank=True, db_column='cname', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cnames', to='mreg.Cname'),
        ),
        migrations.AlterField(
            model_name='cname',
            name='host',
            field=models.ForeignKey(blank=True, db_column='host', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cnames', to='mreg.Host'),
        ),
    ]
