# Generated by Django 2.2 on 2019-04-11 13:45

from django.db import migrations
import netfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mreg', '0004_auto_20190411_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ptroverride',
            name='ipaddress',
            field=netfields.fields.InetAddressField(max_length=39, unique=True),
        ),
    ]
