# Generated by Django 2.1.4 on 2018-12-06 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mreg', '0004_auto_20181205_1100'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='naptr',
            options={'ordering': ('preference', 'order', 'flag', 'service', 'regex', 'replacement')},
        ),
        migrations.AlterModelOptions(
            name='srv',
            options={'ordering': ('name', 'priority', 'weight', 'port', 'target')},
        ),
        migrations.RenameField(
            model_name='naptr',
            old_name='orderv',
            new_name='order',
        ),
        migrations.AlterField(
            model_name='naptr',
            name='replacement',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='naptr',
            name='service',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='srv',
            name='target',
            field=models.CharField(max_length=255),
        ),
        migrations.RemoveField(
            model_name='naptr',
            name='zone',
        ),
        migrations.AlterUniqueTogether(
            name='naptr',
            unique_together={('host', 'preference', 'order', 'flag', 'service', 'regex', 'replacement')},
        ),
    ]
