# Generated by Django 2.2.1 on 2019-05-08 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('mreg', '0004_auto_20190411_1427'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hosts', models.ManyToManyField(related_name='hostgroups', to='mreg.Host')),
                ('owners', models.ManyToManyField(blank=True, to='auth.Group')),
                ('parent', models.ManyToManyField(blank=True, related_name='groups', to='mreg.HostGroup')),
            ],
            options={
                'db_table': 'hostgroup',
                'ordering': ('name',),
            },
        ),
    ]
