# Generated by Django 2.1.7 on 2019-03-19 16:30

from django.db import migrations, models
import django.db.models.deletion
import mreg.validators


class Migration(migrations.Migration):

    dependencies = [
        ('mreg', '0005_auto_20190226_0846'),
    ]

    operations = [
        migrations.CreateModel(
            name='SSHFP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ttl', models.IntegerField(blank=True, null=True, validators=[mreg.validators.validate_ttl])),
                ('algorithm', models.IntegerField(choices=[(1, 'RSA'), (2, 'DSS'), (3, 'ECDSA'), (4, 'Ed25519')])),
                ('hash_type', models.IntegerField(choices=[(1, 'SHA-1'), (2, 'SHA-256')])),
                ('fingerprint', models.CharField(max_length=64, validators=[mreg.validators.validate_hexadecimal])),
                ('host', models.ForeignKey(db_column='host', on_delete=django.db.models.deletion.CASCADE, to='mreg.Host')),
            ],
            options={
                'db_table': 'sshfp',
            },
        ),
    ]
