# Generated by Django 2.0.6 on 2018-07-18 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mreg', '0005_auto_20180713_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='subnets',
            name='reserved',
            field=models.IntegerField(default=3),
        ),
    ]
