# Generated by Django 2.2.7 on 2019-11-05 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mreg', '0005_history'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ModelChangeLog',
        ),
    ]
