# Generated by Django 2.1.7 on 2019-03-05 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mreg', '0005_auto_20190226_0846'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostgroup_name', models.CharField(max_length=50, unique=True)),
                ('parent', models.ManyToManyField(blank=True, related_name='groups', to='mreg.HostGroup')),
            ],
        ),
        migrations.CreateModel(
            name='HostGroupMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mreg.HostGroup')),
                ('host', models.ForeignKey(db_column='host', on_delete=django.db.models.deletion.PROTECT, related_name='hostgroupmembers', to='mreg.Host')),
            ],
        ),
    ]
