# Generated by Django 2.1.4 on 2018-12-07 20:38

from django.db import migrations, models
import django.utils.timezone
import mreg.utils
import mreg.validators


class Migration(migrations.Migration):

    dependencies = [
        ('mreg', '0005_auto_20181206_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='txt',
            name='zone',
        ),
        migrations.AddField(
            model_name='zone',
            name='serialno_updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='zone',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='zone',
            name='serialno',
            field=models.BigIntegerField(default=mreg.utils.create_serialno, validators=[mreg.validators.validate_zones_serialno]),
        ),
    ]
