# Generated by Django 2.1.7 on 2019-04-03 07:41

from django.db import migrations, models
import mreg.validators


class Migration(migrations.Migration):

    dependencies = [
        ('mreg', '0006_sshfp'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetGroupRegexPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=80)),
                ('range', models.TextField(blank=True, validators=[mreg.validators.validate_network])),
                ('regex', models.CharField(max_length=250, validators=[mreg.validators.validate_regex])),
            ],
            options={
                'db_table': 'perm_net_group_regex',
            },
        ),
        migrations.AlterUniqueTogether(
            name='netgroupregexpermission',
            unique_together={('group', 'range')},
        ),
    ]
