# Generated by Django 2.0.6 on 2018-07-19 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mreg', '0006_subnets_reserved'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelChangeLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=132)),
                ('table_row', models.BigIntegerField()),
                ('data', models.TextField()),
                ('action', models.CharField(max_length=16)),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'db_table': 'model_change_logs',
            },
        ),
    ]
