# Generated by Django 2.2.1 on 2019-05-15 12:08

import django.contrib.postgres.fields.citext
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mreg', '0006_auto_20190515_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forwardzone',
            name='email',
            field=django.contrib.postgres.fields.citext.CIEmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='host',
            name='contact',
            field=django.contrib.postgres.fields.citext.CIEmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='reversezone',
            name='email',
            field=django.contrib.postgres.fields.citext.CIEmailField(max_length=254),
        ),
    ]
