# Generated by Django 2.1.4 on 2018-12-11 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mreg', '0006_auto_20181207_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cname',
            name='cname',
            field=models.TextField(unique=True),
        ),
    ]
