# Generated by Django 3.1.1 on 2020-11-17 08:47

from django.db import migrations, models
import mreg.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mreg', '0007_auto_20200905_1410'),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', mreg.fields.LCICharField(max_length=64, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'label',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='netgroupregexpermission',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='permissions', to='mreg.Label'),
        ),
    ]
