# Generated by Django 2.0.6 on 2018-07-23 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mreg', '0007_modelchangelogs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zones',
            name='expire',
            field=models.IntegerField(blank=True, default=604800, null=True),
        ),
        migrations.AlterField(
            model_name='zones',
            name='refresh',
            field=models.IntegerField(blank=True, default=7200, null=True),
        ),
        migrations.AlterField(
            model_name='zones',
            name='retry',
            field=models.IntegerField(blank=True, default=3600, null=True),
        ),
    ]
