# Generated by Django 2.1.4 on 2018-12-12 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mreg', '0007_auto_20181211_1520'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cname',
            old_name='cname',
            new_name='name',
        ),
    ]
