# Generated by Django 2.1.4 on 2018-12-12 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mreg', '0008_auto_20181212_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cname',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
