# Generated by Django 2.0.6 on 2018-07-25 09:34

from django.db import migrations, models
import django.db.models.deletion
import mreg.validators


class Migration(migrations.Migration):

    dependencies = [
        ('mreg', '0008_auto_20180723_1522'),
    ]
    atomic = False

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('hostid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(unique=True)),
                ('contact', models.EmailField(max_length=254)),
                ('ttl', models.IntegerField(blank=True, null=True)),
                ('loc', models.TextField(blank=True, null=True, validators=[mreg.validators.validate_loc])),
                ('comment', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'host',
            },
        ),
        migrations.CreateModel(
            name='Subnet',
            fields=[
                ('subnetid', models.AutoField(primary_key=True, serialize=False)),
                ('range', models.TextField(unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('vlan', models.IntegerField(blank=True, null=True)),
                ('dns_delegated', models.NullBooleanField()),
                ('category', models.TextField(blank=True, null=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('frozen', models.NullBooleanField()),
                ('reserved', models.IntegerField(default=3)),
            ],
            options={
                'db_table': 'subnet',
            },
        ),
        migrations.RenameModel(
            old_name='ModelChangeLogs',
            new_name='ModelChangeLog',
        ),
        migrations.RenameModel(
            old_name='Ns',
            new_name='NameServer',
        ),
        migrations.RenameModel(
            old_name='Zones',
            new_name='Zone',
        ),
        migrations.RemoveField(
            model_name='hosts',
            name='hinfo',
        ),
        migrations.DeleteModel(
            name='Subnets',
        ),
        migrations.AlterField(
            model_name='cname',
            name='hostid',
            field=models.ForeignKey(db_column='hostid', on_delete=django.db.models.deletion.CASCADE, related_name='cname', to='mreg.Host'),
        ),
        migrations.AlterField(
            model_name='ipaddress',
            name='hostid',
            field=models.ForeignKey(db_column='hostid', on_delete=django.db.models.deletion.CASCADE, related_name='ipaddress', to='mreg.Host'),
        ),
        migrations.AlterField(
            model_name='naptr',
            name='hostid',
            field=models.ForeignKey(db_column='hostid', on_delete=django.db.models.deletion.CASCADE, related_name='naptr', to='mreg.Host'),
        ),
        migrations.AlterField(
            model_name='ptroverride',
            name='hostid',
            field=models.ForeignKey(db_column='hostid', on_delete=django.db.models.deletion.CASCADE, related_name='ptr_override', to='mreg.Host'),
        ),
        migrations.AlterField(
            model_name='txt',
            name='hostid',
            field=models.ForeignKey(db_column='hostid', on_delete=django.db.models.deletion.CASCADE, related_name='txt', to='mreg.Host'),
        ),
        migrations.RenameModel(
            old_name='HinfoPresets',
            new_name='HinfoPreset',
        ),
        migrations.AlterModelTable(
            name='hinfopreset',
            table='hinfo_preset',
        ),
        migrations.AlterModelTable(
            name='modelchangelog',
            table='model_change_log',
        ),
        migrations.AlterModelTable(
            name='zone',
            table='zone',
        ),
        migrations.DeleteModel(
            name='Hosts',
        ),
        migrations.AddField(
            model_name='host',
            name='hinfo',
            field=models.ForeignKey(blank=True, db_column='hinfo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mreg.HinfoPreset'),
        ),
    ]
