# Generated by Django 3.1.5 on 2021-03-02 09:37

from django.db import migrations, models
import mreg.fields
import mreg.validators


class Migration(migrations.Migration):

    dependencies = [
        ('mreg', '0008_auto_20201117_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='label',
            name='name',
            field=mreg.fields.LCICharField(max_length=64, unique=True, validators=[mreg.validators.validate_nowhitespace]),
        ),
        migrations.AlterField(
            model_name='txt',
            name='txt',
            field=models.TextField(max_length=4096),
        ),
    ]
