# Generated by Django 2.1.2 on 2018-10-08 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mreg', '0009_auto_20180725_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zone',
            name='email',
            field=models.EmailField(default='foo@foo.no', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='zone',
            name='expire',
            field=models.IntegerField(default=604800),
        ),
        migrations.AlterField(
            model_name='zone',
            name='refresh',
            field=models.IntegerField(default=7200),
        ),
        migrations.AlterField(
            model_name='zone',
            name='retry',
            field=models.IntegerField(default=3600),
        ),
        migrations.AlterField(
            model_name='zone',
            name='ttl',
            field=models.IntegerField(default=43200),
        ),
    ]
