# Generated by Django 2.1.4 on 2018-12-12 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mreg', '0009_auto_20181212_1040'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cname',
            options={'ordering': ('name',)},
        ),
    ]
