# Generated by Django 3.1.3 on 2021-03-30 07:04

from django.db import migrations, models
import django.db.models.deletion
import mreg.validators


class Migration(migrations.Migration):

    dependencies = [
        ('mreg', '0009_auto_20210302_1037'),
    ]

    operations = [
        migrations.CreateModel(
            name='BACnetID',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, validators=[mreg.validators.validate_BACnetID])),
                ('host', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mreg.host')),
            ],
            options={
                'db_table': 'bacnetid',
            },
        ),
    ]
