# Generated by Django 3.2.2 on 2021-05-21 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mreg', '0010_bacnetid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bacnetid',
            name='host',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bacnetid', to='mreg.host'),
        ),
    ]
