# Generated by Django 2.1.2 on 2018-10-09 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mreg', '0010_auto_20181008_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='cname',
            name='zoneid',
            field=models.ForeignKey(blank=True, db_column='zone', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mreg.Zone'),
        ),
        migrations.AddField(
            model_name='host',
            name='zoneid',
            field=models.ForeignKey(blank=True, db_column='zone', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mreg.Zone'),
        ),
        migrations.AddField(
            model_name='naptr',
            name='zoneid',
            field=models.ForeignKey(blank=True, db_column='zone', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mreg.Zone'),
        ),
        migrations.AddField(
            model_name='srv',
            name='zoneid',
            field=models.ForeignKey(blank=True, db_column='zone', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mreg.Zone'),
        ),
        migrations.AddField(
            model_name='txt',
            name='zoneid',
            field=models.ForeignKey(blank=True, db_column='zone', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mreg.Zone'),
        ),
    ]
