# Generated by Django 2.1.4 on 2018-12-20 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mreg', '0010_auto_20181212_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subnet',
            name='dns_delegated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='subnet',
            name='frozen',
            field=models.BooleanField(default=False),
        ),
    ]
