# Generated by Django 2.1.4 on 2018-12-17 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mreg', '0010_auto_20181212_1351'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostgroup_name', models.CharField(max_length=50, unique=True)),
                ('parent', models.ManyToManyField(blank=True, related_name='groups', to='mreg.HostGroup')),
            ],
        ),
        migrations.CreateModel(
            name='HostGroupMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mreg.HostGroup')),
                ('hostid', models.ForeignKey(db_column='hostid', on_delete=django.db.models.deletion.PROTECT, related_name='hostgroupmember', to='mreg.Host')),
            ],
        ),
    ]
