# Generated by Django 2.1.2 on 2018-10-11 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mreg', '0011_auto_20181009_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='txt',
            name='txt',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='zone',
            name='expire',
            field=models.IntegerField(default=1814400),
        ),
        migrations.AlterField(
            model_name='zone',
            name='refresh',
            field=models.IntegerField(default=10800),
        ),
    ]
