# Generated by Django 2.1.2 on 2018-10-25 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mreg', '0012_auto_20181011_1323'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='hinfopreset',
            unique_together={('cpu', 'os')},
        ),
    ]
