# Generated by Django 3.2.18 on 2023-06-29 09:26

from django.db import migrations, models
import mreg.fields
import mreg.validators


class Migration(migrations.Migration):

    dependencies = [
        ('mreg', '0012_expiringtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cname',
            name='name',
            field=mreg.fields.LowerCaseDNSNameField(max_length=253, unique=True, validators=[mreg.validators.validate_hostname]),
        ),
        migrations.AlterField(
            model_name='forwardzone',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='forwardzone',
            name='name',
            field=mreg.fields.LowerCaseDNSNameField(max_length=253, unique=True, validators=[mreg.validators.validate_hostname]),
        ),
        migrations.AlterField(
            model_name='forwardzone',
            name='primary_ns',
            field=mreg.fields.LowerCaseDNSNameField(max_length=253, validators=[mreg.validators.validate_hostname]),
        ),
        migrations.AlterField(
            model_name='forwardzonedelegation',
            name='name',
            field=mreg.fields.LowerCaseDNSNameField(max_length=253, unique=True, validators=[mreg.validators.validate_hostname]),
        ),
        migrations.AlterField(
            model_name='host',
            name='contact',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='host',
            name='name',
            field=mreg.fields.LowerCaseDNSNameField(max_length=253, unique=True, validators=[mreg.validators.validate_hostname]),
        ),
        migrations.AlterField(
            model_name='hostgroup',
            name='name',
            field=mreg.fields.LowerCaseCharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='label',
            name='name',
            field=mreg.fields.LowerCaseCharField(max_length=64, unique=True, validators=[mreg.validators.validate_nowhitespace]),
        ),
        migrations.AlterField(
            model_name='mx',
            name='mx',
            field=mreg.fields.LowerCaseDNSNameField(max_length=253, validators=[mreg.validators.validate_hostname]),
        ),
        migrations.AlterField(
            model_name='nameserver',
            name='name',
            field=mreg.fields.LowerCaseDNSNameField(max_length=253, unique=True, validators=[mreg.validators.validate_hostname]),
        ),
        migrations.AlterField(
            model_name='naptr',
            name='replacement',
            field=mreg.fields.LowerCaseCharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='naptr',
            name='service',
            field=mreg.fields.LowerCaseCharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='reversezone',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='reversezone',
            name='name',
            field=mreg.fields.LowerCaseDNSNameField(max_length=253, unique=True, validators=[mreg.validators.validate_reverse_zone_name]),
        ),
        migrations.AlterField(
            model_name='reversezone',
            name='primary_ns',
            field=mreg.fields.LowerCaseDNSNameField(max_length=253, validators=[mreg.validators.validate_hostname]),
        ),
        migrations.AlterField(
            model_name='reversezonedelegation',
            name='name',
            field=mreg.fields.LowerCaseDNSNameField(max_length=253, unique=True, validators=[mreg.validators.validate_reverse_zone_name]),
        ),
        migrations.AlterField(
            model_name='srv',
            name='name',
            field=mreg.fields.LowerCaseCharField(max_length=255, validators=[mreg.validators.validate_srv_service_text]),
        ),
    ]
