# Generated by Django 2.1.2 on 2018-10-26 10:31

from django.db import migrations, models
import mreg.validators


class Migration(migrations.Migration):

    dependencies = [
        ('mreg', '0013_auto_20181025_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nameserver',
            name='name',
            field=models.CharField(max_length=253, unique=True),
        ),
        migrations.AlterField(
            model_name='zone',
            name='name',
            field=models.CharField(max_length=253, unique=True, validators=[mreg.validators.validate_zonename]),
        ),
    ]
