# Generated by Django 5.0.9 on 2024-11-28 11:39

import datetime
import django.db.models.deletion
import mreg.fields
import mreg.models.policy
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('mreg', '0013_migrate_away_from_ci_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyAtom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('create_date', models.DateField(default=datetime.date.today)),
                ('description', models.CharField(max_length=150)),
                ('name', mreg.fields.LowerCaseCharField(max_length=64, unique=True, validators=[mreg.models.policy._validate_atom_name])),
            ],
            options={
                'db_table': 'policy_atom',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ApprovedModelForPolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'db_table': 'approved_model_for_policy',
            },
        ),
        migrations.CreateModel(
            name='PolicyRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('create_date', models.DateField(default=datetime.date.today)),
                ('description', models.CharField(max_length=150)),
                ('name', mreg.fields.LowerCaseCharField(max_length=64, unique=True, validators=[mreg.models.policy._validate_role_name])),
                ('atoms', models.ManyToManyField(related_name='roles', to='mreg.policyatom')),
                ('labels', models.ManyToManyField(blank=True, related_name='policy_roles', to='mreg.label')),
            ],
            options={
                'db_table': 'policy_role',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='PolicyAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('policy_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='mreg.policyrole')),
            ],
            options={
                'db_table': 'policy_assignment',
            },
        ),
    ]
