# Generated by Django 5.0.9 on 2025-11-12 13:27

import mreg.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mreg', '0014_network_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='max_communities',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='networkpolicy',
            name='community_template_pattern',
            field=models.CharField(blank=True, help_text='Prefix for mapped community names. If not set, the default will be used. This only applies if communities are mapped.', null=True, unique=True, validators=[mreg.validators.validate_community_template_pattern]),
        ),
    ]
