# Generated by Django 2.1.2 on 2018-10-26 13:05

from django.db import migrations, models
import mreg.validators


class Migration(migrations.Migration):

    dependencies = [
        ('mreg', '0014_auto_20181026_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='name',
            field=models.CharField(max_length=253, unique=True, validators=[mreg.validators.validate_hostname]),
        ),
        migrations.AlterField(
            model_name='nameserver',
            name='name',
            field=models.CharField(max_length=253, unique=True, validators=[mreg.validators.validate_hostname]),
        ),
        migrations.AlterField(
            model_name='zone',
            name='primary_ns',
            field=models.CharField(max_length=253, unique=True, validators=[mreg.validators.validate_hostname]),
        ),
    ]
