# Generated by Django 2.1.2 on 2018-10-30 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mreg', '0015_auto_20181026_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subnet',
            name='reserved',
            field=models.PositiveIntegerField(default=3),
        ),
    ]
