# Generated by Django 2.1.2 on 2018-10-31 09:55

from django.db import migrations, models
import mreg.validators


class Migration(migrations.Migration):

    dependencies = [
        ('mreg', '0016_auto_20181030_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zone',
            name='primary_ns',
            field=models.CharField(max_length=253, validators=[mreg.validators.validate_hostname]),
        ),
    ]
