# Generated by Django 6.1.1 on 2026-09-28 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mreg", "0016_host_contacts"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bacnetid",
            options={"verbose_name": "BACnet ID"},
        ),
        migrations.AlterModelOptions(
            name="cname",
            options={"ordering": ("name",), "verbose_name": "CNAME record"},
        ),
        migrations.AlterModelOptions(
            name="community",
            options={
                "ordering": ("name",),
                "verbose_name": "community",
                "verbose_name_plural": "communities",
            },
        ),
        migrations.AlterModelOptions(
            name="expiringtoken",
            options={"verbose_name": "token"},
        ),
        migrations.AlterModelOptions(
            name="forwardzone",
            options={"verbose_name": "forward zone"},
        ),
        migrations.AlterModelOptions(
            name="forwardzonedelegation",
            options={"verbose_name": "forward zone delegation"},
        ),
        migrations.AlterModelOptions(
            name="hinfo",
            options={"verbose_name": "HINFO record"},
        ),
        migrations.AlterModelOptions(
            name="history",
            options={
                "verbose_name": "history entry",
                "verbose_name_plural": "history entries",
            },
        ),
        migrations.AlterModelOptions(
            name="host",
            options={"verbose_name": "host"},
        ),
        migrations.AlterModelOptions(
            name="hostcommunitymapping",
            options={"verbose_name": "host community mapping"},
        ),
        migrations.AlterModelOptions(
            name="hostcontact",
            options={"verbose_name": "host contact"},
        ),
        migrations.AlterModelOptions(
            name="hostgroup",
            options={"ordering": ("name",), "verbose_name": "host group"},
        ),
        migrations.AlterModelOptions(
            name="ipaddress",
            options={
                "verbose_name": "IP address",
                "verbose_name_plural": "IP addresses",
            },
        ),
        migrations.AlterModelOptions(
            name="label",
            options={"ordering": ("name",), "verbose_name": "label"},
        ),
        migrations.AlterModelOptions(
            name="loc",
            options={"verbose_name": "LOC record"},
        ),
        migrations.AlterModelOptions(
            name="mx",
            options={"verbose_name": "MX record"},
        ),
        migrations.AlterModelOptions(
            name="nameserver",
            options={"ordering": ("name",), "verbose_name": "nameserver"},
        ),
        migrations.AlterModelOptions(
            name="naptr",
            options={
                "ordering": (
                    "preference",
                    "order",
                    "flag",
                    "service",
                    "regex",
                    "replacement",
                ),
                "verbose_name": "NAPTR record",
            },
        ),
        migrations.AlterModelOptions(
            name="netgroupregexpermission",
            options={"verbose_name": "netgroup regex permission"},
        ),
        migrations.AlterModelOptions(
            name="network",
            options={"ordering": ("network",), "verbose_name": "network"},
        ),
        migrations.AlterModelOptions(
            name="networkexcludedrange",
            options={
                "ordering": ("start_ip",),
                "verbose_name": "network excluded range",
            },
        ),
        migrations.AlterModelOptions(
            name="networkpolicy",
            options={
                "verbose_name": "network policy",
                "verbose_name_plural": "network policies",
            },
        ),
        migrations.AlterModelOptions(
            name="networkpolicyattribute",
            options={"verbose_name": "network policy attribute"},
        ),
        migrations.AlterModelOptions(
            name="networkpolicyattributevalue",
            options={
                "verbose_name": "network policy attribute value",
                "verbose_name_plural": "network policy attribute values",
            },
        ),
        migrations.AlterModelOptions(
            name="ptroverride",
            options={"verbose_name": "PTR override"},
        ),
        migrations.AlterModelOptions(
            name="reversezone",
            options={"verbose_name": "reverse zone"},
        ),
        migrations.AlterModelOptions(
            name="reversezonedelegation",
            options={"verbose_name": "reverse zone delegation"},
        ),
        migrations.AlterModelOptions(
            name="srv",
            options={
                "ordering": ("name", "priority", "weight", "port", "host"),
                "verbose_name": "SRV record",
            },
        ),
        migrations.AlterModelOptions(
            name="sshfp",
            options={"verbose_name": "SSHFP record"},
        ),
        migrations.AlterModelOptions(
            name="txt",
            options={"verbose_name": "TXT record"},
        ),
    ]
