# Generated by Django 5.2.16 on 2026-09-24 16:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mreg', '0016_host_contacts'),
    ]

    operations = [
        migrations.CreateModel(
            name='SnapshotThrottleState',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('history', models.JSONField(default=list)),
            ],
        ),
    ]
