# Generated by Django 5.2 for MREG's durable policy parity outbox.

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mreg", "0016_host_contacts"),
    ]

    operations = [
        migrations.CreateModel(
            name="PolicyParityOutbox",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("payload", models.JSONField()),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("available_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("locked_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("failed_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("last_error", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "verbose_name_plural": "policy parity outbox entries",
                "indexes": [
                    models.Index(
                        fields=["failed_at", "available_at", "id"],
                        name="policy_outbox_ready_idx",
                    )
                ],
            },
        ),
    ]
