# Generated by Django 2.1.3 on 2018-11-19 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mreg', '0017_auto_20181031_1055'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subnet',
            options={'ordering': ('range',)},
        ),
    ]
