# Generated by Django 2.1.3 on 2018-11-22 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mreg', '0018_auto_20181119_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipaddress',
            name='ipaddress',
            field=models.GenericIPAddressField(),
        ),
        migrations.AlterUniqueTogether(
            name='ipaddress',
            unique_together={('hostid', 'ipaddress')},
        ),
    ]
